import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import MobileNavbar from "@/components/common/MobileNavbar";
import AuthProvider from "@/context/AuthProvider";
import Footer from "@/components/common/Footer";
import MobileFooter from "@/components/common/MobileFooter";
import { Toaster } from "@/components/ui/toaster";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Ashventure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <AuthProvider>
      <body
        className={`${inter.variable} antialiased min-h-screen flex flex-col`}
      >
        <div className='hidden md:block'>
          <Navbar />
        </div>
        <div className='block md:hidden'>
          <MobileNavbar />
        </div>
        {children} 
        <div className='hidden md:block'>
          <Footer />
        </div>
        <div className='block md:hidden'>
            <MobileFooter />
          </div>
          <Toaster/>
      </body>
      </AuthProvider>
    </html>
  );
}
